vim.keymap.set('n', '<C-h>', '<C-w><C-h>', {})
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', {})
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', {})
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', {})
vim.keymap.set('n', ';', ':', {})
vim.keymap.set('t', '<Esc>', '<C-\\><C-n>', {})
vim.keymap.set('n', '<leader>ee', ':Lex<CR>', {})
vim.keymap.set('n', '<leader>ed', ':Lex %:p:h<CR>', {})
vim.keymap.set('n', '<leader>v', ':vsplit<CR>', {})
vim.keymap.set('n', '<leader>h', ':split<CR>', {})
vim.keymap.set('n', '<leader>gg', ':Neogit<CR>', {})
vim.keymap.set('n', '<C-Down>', '<C-w>-<CR>', {})
vim.keymap.set('n', '<C-Up>', '<C-w>+<CR>', {})
vim.keymap.set('n', '<C-Left>', '<C-w>>><CR>', {})
vim.keymap.set('n', '<C-Left>', '<C-w><lt><CR>', {})
